### ISSUE TITLE
Fix Java.Lang.Exception: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:1023)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4775)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2160)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)
 in Crash Group # 992231528u

### ISSUE THREAD

**Issue by CarlosACepeda** [CarlosACepeda/LiveDisplay#109]
### Reason ###

Java.Lang.Exception: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:1023)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4775)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2160)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)

### Link to App Center ###

* [https://appcenter.ms/users/CarlosACepeda/apps/LiveDisplay/crashes/errors/992231528u](https://appcenter.ms/users/CarlosACepeda/apps/LiveDisplay/crashes/errors/992231528u)

**Comment by CarlosACepeda** [comment]
this refers to code that's no longer available
