### ISSUE TITLE
Fix Java.Lang.Exception: Remote stack trace:
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1793)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1770)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1837)
	at android.os.storage.StorageManager.checkExternalStoragePermissionAndAppOp(StorageManager.java:1953)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1919)
 in Crash Group # 1028887240u

### ISSUE THREAD

**Issue by CarlosACepeda** [CarlosACepeda/LiveDisplay#97]
### Reason ###

Java.Lang.Exception: Remote stack trace:
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1793)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1770)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1837)
	at android.os.storage.StorageManager.checkExternalStoragePermissionAndAppOp(StorageManager.java:1953)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1919)

### Link to App Center ###

* [https://appcenter.ms/users/CarlosACepeda/apps/LiveDisplay/crashes/errors/1028887240u](https://appcenter.ms/users/CarlosACepeda/apps/LiveDisplay/crashes/errors/1028887240u)

**Comment by CarlosACepeda** [comment]
this refers to code that's no longer available
